name: pdfwebapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # create pdf document
  pdf: ^3.6.4
  # save pdf in local storage
  path_provider: ^2.1.2

  #open pdf document
  open_file: ^3.3.2

  printing: ^5.9.0


flutter:
  uses-material-design: true
